import { useState } from "react";
import { Link } from "react-router-dom";
import { FileText, ShieldCheck, Globe2, PackageCheck, RefreshCcw, Scale, LockKeyhole, MessageCircle } from "lucide-react";
const sections=[
 {id:"terms",title:"Terms & Conditions",icon:Scale,content:<><p>These terms govern purchases made through the RR MASALA website. Product availability, pricing, shipping, payment, cancellation, returns and export restrictions are subject to the information displayed at checkout and the applicable laws.</p><h3>Orders & pricing</h3><p>RR MASALA uses a single public product selling price in INR. No country-specific product price is configured. International shipping, customs duties, import taxes and carrier charges may differ by destination and are shown or communicated separately where applicable.</p><h3>Product information</h3><p>Product descriptions, ingredients, allergen information, net quantity, shelf life, manufacturer/packer details, FSSAI information and other compliance fields are published only from business-approved data. Customers should check the product label and destination-country requirements before purchase.</p><h3>International orders</h3><p>Acceptance of an international order is subject to destination-country import rules, prohibited/restricted goods, customs clearance and carrier acceptance. The buyer is responsible for destination-country charges unless the checkout explicitly states otherwise.</p></>},
 {id:"privacy",title:"Privacy Policy",icon:LockKeyhole,content:<><p>RR MASALA collects information necessary to provide accounts, orders, delivery, payments, customer support and security. This may include name, mobile number, email, delivery address, order details, device/session information and payment status.</p><h3>Use of data</h3><p>Data is used for order processing, delivery, customer support, fraud/security controls, legal compliance and service communications. Payment credentials are not stored by the RR MASALA application; payment processing is handled by the configured payment provider.</p><h3>Your choices</h3><p>Customers can contact the published grievance/privacy contact for applicable data requests. The final policy and retention periods must be reviewed and approved by the business's legal counsel before production.</p></>},
 {id:"shipping",title:"Shipping & Delivery Policy",icon:PackageCheck,content:<><p>India orders are handled through the configured domestic shipping process. International orders can be classified as AIR or SEA shipments depending on destination, weight, carrier and business approval.</p><h3>Tracking</h3><p>Where a carrier tracking number is available, it is recorded against the order and shown to the customer. Estimated delivery dates are indicative and may change because of customs, carrier delays, weather or other events outside the store's control.</p></>},
 {id:"international",title:"International Shipping & Customs",icon:Globe2,content:<><p>International sales are subject to Indian export requirements, destination-country import requirements and carrier/customs procedures. Commercial invoice, packing list, shipping bill/export documentation, airway bill or bill of lading and certificates may be required depending on the shipment.</p><p>Import duties, VAT/GST, customs fees, inspection charges and other destination-country charges are not automatically included unless the order explicitly states that they are. The exact requirements vary by product and destination.</p></>},
 {id:"returns",title:"Cancellation, Returns & Refunds",icon:RefreshCcw,content:<><p>Customers may request cancellation only while the order is within the permitted cancellation stage. Once an order has reached packing/shipping stages, cancellation may be unavailable.</p><p>For eligible delivered orders, return requests are accepted within the configured return window and subject to product condition, food-safety restrictions and the approved return reason. Perishable/food products should not be represented as universally returnable; the final return policy must specify the eligible circumstances.</p><p>Refunds are processed only after the applicable return/payment verification workflow and are subject to the payment provider's settlement/refund rules.</p></>},
 {id:"food",title:"Food Safety & Product Information",icon:ShieldCheck,content:<><p>RR MASALA publishes food-product information supplied and approved by the business. Pre-packaged food sold online must be presented with the applicable mandatory information before sale, subject to the relevant exceptions in FSSAI rules.</p><p>FSSAI licence/registration details, ingredients, allergens, nutrition, net quantity, manufacturer/packer details, country of origin, shelf-life/best-before information and other applicable declarations should match the approved physical label. Destination-country labelling rules may also apply to exports.</p></>},
 {id:"refund",title:"Payment & Refund Information",icon:FileText,content:<><p>The current project is configured for PhonePe/UPI payments. Payment status is confirmed from the payment provider or merchant verification flow, not from a client-side success screen alone.</p><p>International customers should only be offered payment methods actually enabled for the merchant account and supported for the destination. A domestic UPI-only configuration should not be represented as universal international card/foreign-currency acceptance.</p></>},
 {id:"grievance",title:"Grievance & Contact",icon:MessageCircle,content:<><p>The website should publish the business's actual customer-care and grievance contact details before production. Complaints should receive a trackable reference and be handled within the timelines applicable to the business and law.</p><p><strong>Do not publish placeholder names, phone numbers or registration numbers.</strong> These fields are intentionally configurable and must be filled with verified business information.</p></>},
];
export default function LegalCenter(){const [active,setActive]=useState("terms");const current=sections.find(s=>s.id===active)||sections[0];const CurrentIcon=current.icon;return <main className="legalCenter"><div className="legalHero"><div><span className="eyebrow">RR MASALA · LEGAL & COMPLIANCE</span><h1>Policies & compliance</h1><p>India retail + international export commerce. All business registration numbers, licences and policy contacts must be supplied and legally approved before production.</p></div><ShieldCheck size={52}/></div><div className="legalGrid"><aside className="legalNav">{sections.map(s=>{const I=s.icon;return <button key={s.id} className={active===s.id?"active":""} onClick={()=>setActive(s.id)}><I size={17}/><span>{s.title}</span></button>})}</aside><article className="legalArticle"><div className="legalTitle"><CurrentIcon size={22}/><h2>{current.title}</h2></div>{current.content}<div className="legalNotice"><strong>Legal review required</strong><span>This website content is a structured product/commerce template, not a legal opinion. The business's advocate/CA/CS/export consultant should approve the final wording, registrations and destination-country requirements before launch.</span></div></article></div><div className="legalLinks"><Link to="/products">Browse products</Link><Link to="/contact">Contact RR MASALA</Link></div></main>}
