export const ORDER_STATUSES=['PENDING','CONFIRMED','PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'];
export const CANCELLABLE_STATUSES=new Set(['PENDING','CONFIRMED','PROCESSING']);
export const canCancelOrder=order=>CANCELLABLE_STATUSES.has(order?.orderStatus);
