import mongoose from "mongoose"; import Order from "../models/Order.js"; import Cart from "../models/Cart.js"; import Product from "../models/Product.js"; import OrderStatusHistory from "../models/OrderStatusHistory.js"; import Notification from "../models/Notification.js"; import ReturnModel from "../models/Return.js"; import {nextOrderNumber} from "../utils/orderNumber.js"; import {decrement,increment} from "../services/inventoryService.js"; import {sendNewOrderNotification,sendOrderStatusNotification,getWhatsappFallback,formatOrderMessage} from "../services/whatsappService.js"; import {env} from "../config/env.js";
const noCancel=["PACKED","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"];
function countryOf(a){return String(a?.country||"India").trim();}
function isIndia(c){return ["india","in","ind"].includes(String(c||"").toLowerCase());}
function shippingFor(orderType,method,subtotal){ if(orderType==="DOMESTIC") return subtotal>=env.freeShippingThreshold?0:env.shippingFee; if(method==="AIR") return env.internationalAirShippingFee; return env.internationalSeaShippingFee; }
function validateAddress(a,orderType,method){ if(!a?.fullName||!a?.mobile||!a?.address||!a?.city||!a?.state||!a?.pincode||!a?.country) throw Object.assign(new Error("Complete delivery address is required"),{status:422}); if(orderType==="INTERNATIONAL"&&!['AIR','SEA'].includes(method)) throw Object.assign(new Error("Choose AIR or SEA shipping for international orders"),{status:422}); }
export async function create(req,res,next){let session;try{const {shippingAddress,paymentMethod="UPI",shippingMethod="DOMESTIC",notes}=req.body;const country=countryOf(shippingAddress);const orderType=isIndia(country)?"DOMESTIC":"INTERNATIONAL";const method=orderType==="DOMESTIC"?"DOMESTIC":shippingMethod;validateAddress({...shippingAddress,country},orderType,method);if(!["UPI","PHONEPE"].includes(paymentMethod))return res.status(422).json({success:false,message:"Only PhonePe/UPI payments are enabled for this store."});
 const cart=await Cart.findOne({user:req.user._id}).populate("items.product");if(!cart?.items?.length)return res.status(400).json({success:false,message:"Cart is empty"});
 const items=cart.items.map(i=>{if(!i.product||!i.product.isActive)throw Object.assign(new Error("One or more products are unavailable"),{status:409});const max=Number(i.product.maxOrderQuantity||10);if(i.quantity>max)throw Object.assign(new Error(`${i.product.name} has a maximum order quantity of ${max}`),{status:409});return {product:i.product._id,name:i.product.name,sku:i.product.sku,image:i.product.thumbnail||i.product.images?.[0],quantity:i.quantity,price:i.product.price,weight:i.product.weight?`${i.product.weight} ${i.product.weightUnit||""}`:""};});
 const subtotal=items.reduce((s,i)=>s+i.price*i.quantity,0);const discount=0;const shippingFee=shippingFor(orderType,method,subtotal);const tax=0;const grandTotal=subtotal+shippingFee;
 session=await mongoose.startSession();let order;await session.withTransaction(async()=>{await decrement(items,session);order=await Order.create([{orderNumber:await nextOrderNumber(Order),customer:req.user._id,items,shippingAddress:{...shippingAddress,country},billingAddress:{...shippingAddress,country},orderType,shippingMethod:method,currency:"INR",subtotal,discount,tax,shippingFee,grandTotal,paymentMethod,paymentProvider:"PHONEPE",notes,paymentExpiresAt:new Date(Date.now()+30*60*1000)}],{session}).then(x=>x[0]);await Cart.findOneAndUpdate({user:req.user._id},{items:[]},{session});await OrderStatusHistory.create([{order:order._id,oldStatus:"",newStatus:"PENDING",changedBy:req.user._id,note:`${orderType} order · ${method}`}],{session});await Notification.create([{user:req.user._id,title:"Order placed",message:`Your order ${order.orderNumber} has been placed and is awaiting payment.`,type:"ORDER"}],{session});});session.endSession();session=null;const full=await Order.findById(order._id).populate("customer","name mobile email");const wa=await sendNewOrderNotification(full);order.whatsappStatus=wa.status;await order.save();req.app.get("io")?.to(`user:${req.user._id}`).emit("order:created",full);req.app.get("io")?.to("admins").emit("order:created",full);res.status(201).json({success:true,data:{order:full,whatsappUrl:wa.url||getWhatsappFallback(full),whatsappMessage:formatOrderMessage(full)}});
 }catch(e){if(session)try{await session.abortTransaction();session.endSession();}catch{} next(e)}}
export async function mine(req,res,next){try{const items=await Order.find({customer:req.user._id}).sort({createdAt:-1});res.json({success:true,data:{items}})}catch(e){next(e)}}
export async function getOne(req,res,next){try{const p=req.user.role==='ADMIN'||req.user.role==='STAFF'?{}:{customer:req.user._id};const o=await Order.findOne({_id:req.params.id,...p}).populate('customer','name email mobile');if(!o)return res.status(404).json({success:false,message:'Order not found'});const history=await OrderStatusHistory.find({order:o._id}).sort({createdAt:1});res.json({success:true,data:{order:o,history}})}catch(e){next(e)}}
export async function cancel(req,res,next){try{const o=await Order.findOne({_id:req.params.id,customer:req.user._id});if(!o)return res.status(404).json({success:false,message:'Order not found'});if(noCancel.includes(o.orderStatus))return res.status(403).json({success:false,message:'Order cannot be cancelled at this stage.'});if(o.paymentStatus==='PAID')return res.status(403).json({success:false,message:'Paid orders require refund processing before cancellation.'});const old=o.orderStatus;o.orderStatus='CANCELLED';o.cancelReason=req.body.reason||'Customer requested cancellation';if(!o.stockReleasedAt){await increment(o.items);o.stockReleasedAt=new Date();}o.paymentStatus='CANCELLED';await o.save();await OrderStatusHistory.create({order:o._id,oldStatus:old,newStatus:'CANCELLED',changedBy:req.user._id,note:o.cancelReason});req.app.get('io')?.to(`user:${req.user._id}`).emit('order:cancelled',o);res.json({success:true,data:{order:o}})}catch(e){next(e)}}
export async function adminList(req,res,next){try{const {status,q,country,orderType}=req.query;const filter={};if(status)filter.orderStatus=status;if(orderType)filter.orderType=orderType;if(country)filter['shippingAddress.country']=new RegExp(country,'i');if(q)filter.$or=[{orderNumber:new RegExp(q,'i')},{paymentTransactionId:new RegExp(q,'i')}];const items=await Order.find(filter).populate('customer','name mobile email').sort({createdAt:-1}).limit(500);res.json({success:true,data:{items}})}catch(e){next(e)}}
export async function status(req,res,next){try{const o=await Order.findById(req.params.id).populate('customer','name mobile email');if(!o)return res.status(404).json({success:false,message:'Order not found'});const {status,note,trackingNumber,carrier,estimatedDelivery}=req.body;if(!status)return res.status(422).json({success:false,message:'Status required'});const old=o.orderStatus;o.orderStatus=status;if(trackingNumber!==undefined)o.trackingNumber=trackingNumber;if(carrier!==undefined)o.carrier=carrier;if(estimatedDelivery!==undefined)o.estimatedDelivery=estimatedDelivery;if(status==='CANCELLED'&&!o.stockReleasedAt){await increment(o.items);o.stockReleasedAt=new Date();if(o.paymentStatus==='PENDING')o.paymentStatus='CANCELLED';}await o.save();await OrderStatusHistory.create({order:o._id,oldStatus:old,newStatus:status,changedBy:req.user._id,note});const n=await Notification.create({user:o.customer._id,title:`Order ${status.replaceAll('_',' ')}`,message:`Your order ${o.orderNumber} is now ${status.replaceAll('_',' ').toLowerCase()}.`,type:'ORDER'});req.app.get('io')?.to(`user:${o.customer._id}`).emit('order:statusChanged',{order:o,notification:n});req.app.get('io')?.to('admins').emit('order:updated',o);await sendOrderStatusNotification(o);res.json({success:true,data:{order:o}})}catch(e){next(e)}}
export async function requestReturn(req,res,next){try{const o=await Order.findOne({_id:req.params.id,customer:req.user._id,orderStatus:'DELIVERED'});if(!o)return res.status(400).json({success:false,message:'Return is available only for delivered orders'});const days=(Date.now()-new Date(o.updatedAt).getTime())/(86400000);if(days>env.returnWindowDays)return res.status(400).json({success:false,message:`Return window of ${env.returnWindowDays} days has expired`});const r=await ReturnModel.create({order:o._id,customer:req.user._id,item:req.body.item,quantity:req.body.quantity,reason:req.body.reason,description:req.body.description,image:req.body.image});o.returnStatus='REQUESTED';await o.save();req.app.get('io')?.to('admins').emit('order:returnUpdated',r);res.status(201).json({success:true,data:{returnRequest:r}})}catch(e){next(e)}}
export async function adminReturn(req,res,next){try{const r=await ReturnModel.findById(req.params.id).populate('customer','name email mobile');if(!r)return res.status(404).json({success:false,message:'Return not found'});r.status=req.body.status;await r.save();await Order.findByIdAndUpdate(r.order,{returnStatus:r.status});req.app.get('io')?.to(`user:${r.customer._id}`).emit('order:returnUpdated',r);res.json({success:true,data:{returnRequest:r}})}catch(e){next(e)}}
