import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import morgan from "morgan";
import { env } from "./config/env.js";
import auth from "./routes/auth.js";
import products from "./routes/products.js";
import categories from "./routes/categories.js";
import cart from "./routes/cart.js";
import orders from "./routes/orders.js";
import users from "./routes/users.js";
import dashboard from "./routes/dashboard.js";
import adminMisc from "./routes/adminMisc.js";
import wishlist from "./routes/wishlist.js";
import payments from "./routes/payments.js";
import { notFound, errorHandler } from "./middleware/error.js";
const app = express();
app.set("trust proxy", 1);
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin(origin, cb){ if(!origin || env.clientUrls.includes(origin)) return cb(null,true); return cb(new Error("CORS origin not allowed")); }, credentials:true }));
app.use(express.json({ limit: "5mb" }));
app.use(express.urlencoded({ extended: true, limit: "2mb" }));
app.use(cookieParser());
app.use(morgan("dev"));
app.use(rateLimit({ windowMs:15*60*1000, max:500, standardHeaders:true, legacyHeaders:false }));
app.get("/api/health", (req,res)=>res.json({success:true,message:"RR MASALA API online",time:new Date().toISOString()}));
app.use("/api/auth", auth);
app.use("/api/products", products);
app.use("/api/categories", categories);
app.use("/api/cart", cart);
app.use("/api/wishlist", wishlist);
app.use("/api/orders", orders);
app.use("/api/payments", payments);
app.use("/api/users", users);
app.use("/api/admin/dashboard", dashboard);
app.use("/api/admin", adminMisc);
app.use(notFound);
app.use(errorHandler);
export default app;
